### ISSUE TITLE
Hey !

### ISSUE THREAD

**Issue by FGRibreau** [paegun/rrrmatey#1]
Hello @paegun !

Nice work! RRRMatey will be shared in our next [RedisWeekly](http://redisweekly.com)!

**Comment by paegun** [comment]
Thank you @FGRibreau . I look forward to each week's digest of the community around the data server that helps you think in terms of data. Rock on [RedisWeekly](http://redisweekly.com).

**Comment by FGRibreau** [comment]
Hello @paegun !

Thanks a lot for your feedback, [I added it to our homepage](http://redisweekly.com/), I hope that's fine with you?

Have a nice day!
